### ISSUE TITLE
lang=scss in vue single file component cause Module build failed  

### ISSUE THREAD

**Issue by mepanko91** [mubaidr/vue-electron-template#1132]
I wrote this in a vue single file component which cause error. I need SASS syntax so please help.

`<style lang="scss" scoped>
    .v-card__actions {
        flex-flow: wrap;
    }
</style>`

If I remove lang="scss" then it works.
I am using vuetify. 

`ERROR in ./src/renderer/components/single-job-navigation.vue?vue&type=style&index=0&id=6fb86653&lang=scss&scoped=true& (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/vue-style-loader/index.js!./node_modules/css-loader/dist/cjs.js!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-4[0].rules[0].use[3]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/renderer/components/single-job-navigation.vue?vue&type=style&index=0&id=6fb86653&lang=scss&scoped=true&)

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ReferenceError: document is not defined
    at addStyle (webpack-internal:///./node_modules/vue-style-loader/lib/addStylesClient.js:125:22)
    at addStylesToDom (webpack-internal:///./node_modules/vue-style-loader/lib/addStylesClient.js:109:20)
    at addStylesClient (webpack-internal:///./node_modules/vue-style-loader/lib/addStylesClient.js:63:3)
    at eval (webpack-internal:///./node_modules/vue-style-loader/index.js!./node_modules/css-loader/dist/cjs.js!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-4[0].rules[0].use[3]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/renderer/components/single-job-navigation.vue?vue&type=style&index=0&id=6fb86653&lang=scss&scoped=true&:10:14)
    at Object../node_modules/vue-style-loader/index.js!./node_modules/css-loader/dist/cjs.js!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-4[0].rules[0].use[3]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/renderer/components/single-job-navigation.vue?vue&type=style&index=0&id=6fb86653&lang=scss&scoped=true& (C:\Users\home\Desktop\electron\node_modules\vue-style-loader\index.js!C:\Users\home\Desktop\electron\node_modules\css-loader\dist\cjs.js!C:\Users\home\Desktop\electron\node_modules\vue-loader\lib\loaders\stylePostLoader.js!C:\Users\home\Desktop\electron\node_modules\sass-loader\dist\cjs.js??clonedRuleSet-4[0].rules[0].use[3]!C:\Users\home\Desktop\electron\node_modules\vue-loader\lib\index.js??vue-loader-options!C:\Users\home\Desktop\electron\src\renderer\components\single-job-navigation.vue?vue&type=style&index=0&id=6fb86653&lang=scss&scoped=true&:51:1)
    at __webpack_require__ (C:\Users\home\Desktop\electron\node_modules\vue-style-loader\index.js!C:\Users\home\Desktop\electron\node_modules\css-loader\dist\cjs.js!C:\Users\home\Desktop\electron\node_modules\vue-loader\lib\loaders\stylePostLoader.js!C:\Users\home\Desktop\electron\node_modules\sass-loader\dist\cjs.js??clonedRuleSet-4[0].rules[0].use[3]!C:\Users\home\Desktop\electron\node_modules\vue-loader\lib\index.js??vue-loader-options!C:\Users\home\Desktop\electron\src\renderer\components\single-job-navigation.vue?vue&type=style&index=0&id=6fb86653&lang=scss&scoped=true&:99:42)
    at C:\Users\home\Desktop\electron\node_modules\vue-style-loader\index.js!C:\Users\home\Desktop\electron\node_modules\css-loader\dist\cjs.js!C:\Users\home\Desktop\electron\node_modules\vue-loader\lib\loaders\stylePostLoader.js!C:\Users\home\Desktop\electron\node_modules\sass-loader\dist\cjs.js??clonedRuleSet-4[0].rules[0].use[3]!C:\Users\home\Desktop\electron\node_modules\vue-loader\lib\index.js??vue-loader-options!C:\Users\home\Desktop\electron\src\renderer\components\single-job-navigation.vue?vue&type=style&index=0&id=6fb86653&lang=scss&scoped=true&:155:37
    at Object.<anonymous> (C:\Users\home\Desktop\electron\node_modules\vue-style-loader\index.js!C:\Users\home\Desktop\electron\node_modules\css-loader\dist\cjs.js!C:\Users\home\Desktop\electron\node_modules\vue-loader\lib\loaders\stylePostLoader.js!C:\Users\home\Desktop\electron\node_modules\sass-loader\dist\cjs.js??clonedRuleSet-4[0].rules[0].use[3]!C:\Users\home\Desktop\electron\node_modules\vue-loader\lib\index.js??vue-loader-options!C:\Users\home\Desktop\electron\src\renderer\components\single-job-navigation.vue?vue&type=style&index=0&id=6fb86653&lang=scss&scoped=true&:158:12)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at evalModuleCode (C:\Users\home\Desktop\electron\node_modules\mini-css-extract-plugin\dist\utils.js:41:10)
    at C:\Users\home\Desktop\electron\node_modules\mini-css-extract-plugin\dist\loader.js:317:51
    at C:\Users\home\Desktop\electron\node_modules\webpack\lib\Compiler.js:538:11
    at C:\Users\home\Desktop\electron\node_modules\webpack\lib\Compiler.js:1106:17
    at Hook.eval [as callAsync] (eval at create (C:\Users\home\Desktop\electron\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\home\Desktop\electron\node_modules\tapable\lib\Hook.js:18:14)
    at C:\Users\home\Desktop\electron\node_modules\webpack\lib\Compiler.js:1102:33
 @ ./src/renderer/components/single-job-navigation.vue?vue&type=style&index=0&id=6fb86653&lang=scss&scoped=true& 1:0-469 1:0-469
 @ ./src/renderer/components/single-job-navigation.vue 4:0-106
 @ ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js??vue-loader-options!./src/renderer/App.vue?vue&type=script&lang=js& 10:50-95
 @ ./src/renderer/App.vue?vue&type=script&lang=js& 1:0-163 1:179-182 1:184-344 1:184-344
 @ ./src/renderer/App.vue 2:0-55 3:0-50 3:0-50 9:2-8
 @ ./src/renderer/main.js 5:34-54`

**Comment by mubaidr** [comment]
This seems to be caused by `mini-css-extract-plugin` plugin for webpack. Try disabling it.

**Comment by mepanko91** [comment]
I commented mini-css-extract-plugin in \_scripts\webpack.renderer.config.js and the error is gone. Thanks
```
      {
        test: /\.vue$/,
        loader: 'vue-loader',
      },
      {
        test: /\.s(c|a)ss$/,
        use: [
          // {
          //   loader: MiniCssExtractPlugin.loader,
          // },
          'vue-style-loader',
          {
            loader: 'css-loader',
          },
          {
            loader: 'sass-loader',
            options: {
              // eslint-disable-next-line
              implementation: require('sass'),
            },
          },
        ],
      },
```
